name: mediapipe
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - nb_conda_kernels=2.3.1
  - opencv=4.0.1
  - scikit-learn=0.24.2
  - tensorflow=2.3.0  
  - pandas=1.2.5 
  - numpy=1.20.3
  - h5py=2.10.0  
  - matplotlib=3.3.4
  - pip=21.1.3
  - pip:
    - mediapipe==0.8.6




